### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by ThomasKaiser** [apritzel/peekpoke#1]
Tried it with both GCC 5.4 and 6.2 directly on Pine64 with Ubuntu 16.04 and get always

    peekpoke.c: In function ‘parse_range’:
    peekpoke.c:95:12: error: ‘s’ undeclared (first use in this function)
            if (s[i++] != '[')
                ^
    peekpoke.c:95:12: note: each undeclared identifier is reported only once for each function it appears in

What am I'm doing wrong?

**Comment by ehoutsma** [comment]
I believe there is a small typo at line 90. The function call says : const char *str but the value s is being used, so I changed str to s and it works like a charm.

**Comment by ThomasKaiser** [comment]
> so I changed str to s and it works like a charm

Yes, that did the trick. Thank you!

**Comment by apritzel** [comment]
Arrgh, sorry for that and thanks @ThomasKaiser for the report.
This is due to some rebasing issue. Seems I violated publishing rule #17:
"Always tests the very version of the code that you send out".

Fixed in the current HEAD.

**Comment by ThomasKaiser** [comment]
BTW: Even with current HEAD the tool segfaults when doing `./peekpoke r.l 0x1c00030`. Not that important for me since by choosing insane rx-delay values I already confirmed that writing works (immediately locked out of Pine64 after applying stupid settings :) )

**Comment by apritzel** [comment]
Seems like I was so fascinated by my -b option that I never actually tested it without it :-(
So can you try: `./peekpoke -b 0x1c00000 r.l 0x30` instead?

Will fix the original bug later. Thanks for the report!

**Comment by ThomasKaiser** [comment]
With correct syntax it works as expected:

    root@pine64:~# peekpoke -b 0x1c00000 r.l 0x30
    0x50806
    root@pine64:~# peekpoke -b 0x1c00000 B[12:10].l 0x30 3 B[9:5].l 0x30 0 r.l 0x30
    0x50c06
    root@pine64:~# peekpoke -b 0x1c00000 r.l 0x30
    0x50c06
