### ISSUE TITLE
Compilation warning

### ISSUE THREAD

**Issue by rbalykov** [apritzel/peekpoke#2]
peekpoke.c:283:57: warning: the omitted middle operand in ‘?:’ will always be ‘true’, suggest explicit middle operand [-Wparentheses]

**Comment by apritzel** [comment]
Thanks for the report, and indeed: newer GCCs complain. Looking closer this was actually wrong anyway, although working by chance (if read_only is true, it's 1, which is the same as PROT_READ).
Fixed in  d056ff7090de9e1d4ccd36c5a6d365c779f8505b.
